import "server-only"
import './globals.css'
import Navbar  from '../components/Navbar'
import SupabaseProvider from '@/components/providers/supabase-provider'
import SupabaseAuthProvider from '@/components/providers/supabase-auth-provider'
import createClient from '@/utils/supabase-server'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

	const supabase = createClient();

	const { data : {
		session
	} } = await supabase.auth.getSession()

  return (
    <html lang="en">
      <body className="bg-gradient-to-tr from-black via-blue-950 to-black from-30% bg-opacity-75">
			<SupabaseProvider>
				<SupabaseAuthProvider serverSession={session}>
					{children}
				</SupabaseAuthProvider>
			</SupabaseProvider>
	  </body>
    </html>
  )
}
