import './globals.css'
import Navbar  from '../components/Navbar'
import SupabaseProvider from '@/components/providers/supabase-provider'
import SupabaseAuthProvider from '@/components/providers/supabase-auth-provider'
import createClient from '@/utils/supabase-server'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

	const supabase = createClient();

	const { data : {
		session
	} } = await supabase.auth.getSession()

  return (
    <html lang="en">
      <body>
		<Navbar />
		<SupabaseProvider>
			<SupabaseAuthProvider serverSession={session}>
				{children}
			</SupabaseAuthProvider>
		</SupabaseProvider>
	  </body>
    </html>
  )
}
